proxy_test.go

We do not need to parse flags for UT.
This should fix the CI failure in https://travis-ci.org/kata-containers/proxy/builds/308886984?utm_source=github_status&utm_medium=notification

fix UT data race

---

.pullapprove.yml
.travis.yml
Makefile
README.md

For travis build results and codecov coverage.
For pullapprove, the proxy team will be the PR gatekeepers.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

Add README build and coverage badges, enable pullapprove

---

proxy.go

Failing to dial the mux address would result in an incorrectly
formatted error message due to calling `logrus.Fail()` rather than
`logrus.Failf()`.
Also improved wording and quoted the address string.

error: Fix error formatting and improve message

---

Makefile

Create the binary as "kata-proxy" for parity with the convention
used by other system elements.

build: Name the binary "kata-proxy"

---

.gitignore
Makefile
VERSION
proxy.go

build: Add version details to binary
Generate a version string containing version number and commit that the
proxy logs when initialising the logger or when the user specifies
"-version".

Add version details

---

Makefile

In order to install the kata-proxy binary from the Makefile, this
commit adds a new entry "install" to it.
Fixes #21
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

makefile: Add "install" case

---

proxy.go

Ensure log entries specify the name of the proxy, not its path.
Fixes #28.

logger: Fix syslog identifier.

---

proxy_test.go

Fix `gometalinter` errors that would cause the CI to fail.
Fixes #30.

CI: Fix lint errors

---

.ci/lib.sh
.ci/static-checks.sh
.travis.yml
Makefile

Run the static checks defined in the tests repository. Currently, this
just runs the `checkcommits` tool that requires all PRs to contain a
"Fixes #XXX" comment and a "Signed-off-by:" comment.
Fixes #16.

CI: Enable centralised static checks

---

.ci/go-test.sh
.ci/lib.sh
Makefile

Use the central hack/go-test.sh in the tests repo for consistency.
Fixes #32.
Signed-off-by: Shuquan Huang <huang.shuquan@99cloud.net>

Use central go test script

---

proxy.go

-mux-socket and -listen-socket needed when running kata-proxy, print a more useful help
message if required options are not specified

Print the correct usage for required options

---

.ci/run.sh
.ci/setup.sh

.ci/setup.sh will setup the environment with
latest changes to be able to execute Kata Containers.
.ci/run.sh will execute the integration tests that live
in the 'kata-containers/tests' repository.
Fixes: #55.

CI: add setup.sh and run.sh to execute integration tests

---

proxy.go

Switch from second resolution to nanosecond resolution log entries.
Fixes #49.

logger: Use nanosecond timestamps

---

proxy.go

Add a new "source" log field to allow logs coming from the agent to be
distinguished from logs coming direct from the proxy.
Fixes #51.

logging: Add agent source log field

---

fatal.go
proxy.go

If the proxy fails due to an internal error or if it receives
a fatal signal, write a stack trace to the log and exit.
If it was started with `--debug` also dump core.
Fixes #59.

main: stacktrace/coredump on error

---

proxy.go

We don't know how much time a container can be paused, hence connection
write timeout should be disabled to don't close the connection while
the container is paused.
fixes kata-containers/agent#231
fixes #70
Signed-off-by: Julio Montes <julio.montes@intel.com>

disable yamux keep alive

---

.ci/lib.sh

Now static-checks.sh needs to have the
repository name as arguments.
Fixes #79.

CI: update static-checks.sh

---

.travis.yml
signals.go

Fixes #75
According to the man 7 page on Linux the signal is not used. Further, it is not defined on Darwin.
This makes the build compile both on Linux and Darwin.

signal: Removed SIGSTKFLT

---

.travis.yml

Fixes: #83
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com

travis: Enable travis ci for ppc64le

---

proxy.go

Use the standard `logrus.WithError()` API to handle logging of all
errors.
Also, rather than just returning (or continuing in some cases), always `exit(1)` on fatal error to indicate failure.
Fixes #85.

logging: Use WithError() for all errors

---

.travis.yml
proxy.go
proxy_test.go

Added a new `-sandbox` command-line option. This is not required by the
proxy itself, but is used to add a `sandbox` log field to make log
analysis easier.
Also changed the initial log message to show the standard "announce" message tag along with fields for each of the command-line options.
Fixes #87.

logging: Add sandbox CLI option

---

proxy.go

We are trying to disable the feature keepalive introduced by Yamux
both on the client (kata-proxy) and server (kata-agent) sides. The
reason being we don't want to get Yamux errors in case we pause the
VM. The proxy side has already been disabled and we are about to
disable it on the agent side too. Problem is, we sometimes run into
a weird issue where the communication between the proxy and the agent
hangs.
It's related to the emulated serial port created by Qemu which is not
getting out of its sleeping loop for some cases. This issue is still
under investigation, but a simple fix is to actually write more data
to the serial port to wake it up. This workaround is needed since
disabling Yamux keepalive solves several issues, particularly one
related to our long running soak tests.
That's …

proxy: Maintain communication state with a heartbeat

---

proxy.go
proxy_test.go

When cleaning up, we need to make sure the yamux session is closed as
well. It does not close the session by just closing the listener.
OTOH, it closes all streams if the session is closed.
Fixes: #93

proxy: close yamux session properly

---

proxy.go

Capture yamux messages to the logger.
Fixes #88.

logging: Redirect yamux warnings/errors to logger

---

proxy.go

Correct an invalid use of the logger where an argument was passed to
`Debug()` (should have been `Debugf()`) by using of `WithError()`
instead.
Fixes #98.

logging: Fix incorrect logger usage

---

Makefile

Add DESTDIR variable, by default the path is `/` (root).
If defined the kata-proxy will be intalled in the new destination
defined there.
Fixes: #101

Makefile: Add DESTDIR variable support.

---

.travis.yml
Makefile
proxy.go
proxy_test.go

analyzed each patch from HEAD (6f209b7) to 1.1.0.
Analysis:
1.1.1 | * 494d0d8 Makefile: Add DESTDIR variable support.
1.1.1 | * 7fd3734 logging: Fix incorrect logger usage
1.1.1 | * ec252d8 logging: Redirect yamux warnings/errors to logger
1.1.1 | * 1fbb8b3 proxy: wait copy goroutine to quit
1.1.1 | * 22c6f40 proxy: close yamux session properly
NO *   c416c9f Merge pull request #91 from sboeuf/introduce_heartbeat_yamux
| * 063d58f proxy: Maintain communication state with a heartbeat
NO   | * 1672418 logging: Add sandbox CLI option
1.1.1 | * 9b6bb05 logging: Display standard announce message
1.1.1 | * 246f707 CI: Update bash on Travis OSX for hashes
1.1.1 | * 73dbb10 logger: Die if unable to create syslog hook
1.1.1 | * 0cfa402 main: Exit on fatal error
1.1.1 | * 7681a94 logging: Use …

Stable 1.1.1 candidate

---

Makefile

pull in relevant changes from HEAD (6f209b7) to 1.2.0.
Only a single patch, | * 494d0d8 Makefile: Add DESTDIR variable support.

stable 1.2.1 release candidate

---

Makefile

If the VERSION file changes, rebuild.
This was found whilst switching between versions that had identical
sources, but not VERSION files.
Fixes: #121
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

Makefile: trigger build on VERSION file changes

---

Makefile

Build the proxy binary as Position-Independent-Executable (PIE) for improved
security and compliancy with distros packaging guidelines.
Fixes: #123

proxy: build as Position-Independent-Executable

---

Makefile

Define and interpret LIBEXECDIR as an absolute path,
to be consistent with the commonly accepted way to define
it in GNU make projects.
Fixes: #125

make: interpret LIBEXECDIR as an absolute path

---

CODEOWNERS

Add a CODEOWNERS file, explicitly listing the
@kata-containers/documentation group as the owners
of all *.md files.
This is used as part of the github 'review and ack' automated
process.
Fixes: #134
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

CI: add a CODEOWNERS file

---

README.md

Add a link in the rather sparse top level proxy README
file off to the relevant architecture documentation.
Fixes: #136
Signed-off-by: Graham Whaley <graham.whaley@intel.com>

docs: Add arch link to README file

---

proxy_test.go

gometalinter is deprecated and will be archived April '19. The
suggestion is to switch to golangci-lint which is apparently 5x faster
than gometalinter.
Partially fixes: github.com/kata-containers/runtime#1377

lint: Switch golang linter to golangci-lint

---

README.md

The old url, return 404 when accessing

Fix the url of the Kata Containers architecture documentation

---

.travis.yml

Update go version used in travis from 1.10 to 1.11
Fixes: #168.

travis: Update go version on travis

---

README.md

The URL for has changed, lets update it.
Fixes: #171

[stable-1.5]docs: Update architecture doc  URL

---

.travis.yml
README.md
proxy_test.go

Backport includes below changes.
https://github.com/kata-containers/proxy/pull/172
https://github.com/kata-containers/proxy/pull/169
https://github.com/kata-containers/proxy/pull/155

backport: 1.6.2 backport patches

---

.travis.yml

Instead of old trusty distribution.
Fixes: #224.

ci: travis: use xenial

---

Makefile

Allow scripts overwrite PREFIX from environment in order to install proxy in a
specific path
fixes #228
Signed-off-by: Julio Montes <julio.montes@intel.com>

Makefile: overwrite PREFIX from environment

---

Makefile

Allow scripts overwrite PREFIX from environment in order to install proxy in a
specific path
fixes #228
Signed-off-by: Julio Montes <julio.montes@intel.com>

[backport 1.9] Makefile: overwrite PREFIX from environment

---

Makefile

Allow scripts overwrite PREFIX from environment in order to install proxy in a
specific path
fixes #228
Signed-off-by: Julio Montes <julio.montes@intel.com>

[backport 1.10] Makefile: overwrite PREFIX from environment

---

Makefile

This provide a flag "STRIP=yes" to strip the golang binary
Fixs: #236
Signed-off-by: Jia He <justin.he@arm.com>

build: Add support to strip the proxy golang binary

---

.travis.yml

Specify golang 1.13.9 in travis file and delete call to the
`.ci/install_go.sh` script as it is not working properly
in travis environment.
Fixes: #247.

travis: specify golang version

---

.github/workflows/move-issues-to-in-progress.yaml
.github/workflows/require-pr-porting-labels.yaml

Change the following two GitHub actions (which operate on PRs) so that
they will only trigger once new PRs have been manually reviewed:
| GitHub Action | Summary | Reason `pull_request_target` event needed |
|-|-|-|
| `move-issues-to-in-progress.yaml` | Moves issues to the "In progress" column in the ["Issue backlog" project](https://github.com/orgs/kata-containers/projects/23). | Required to determine linked issue for a PR using the GitHub API. |
| `require-pr-porting-labels.yaml` | Performs checks on each PR to ensure they confirm to the [porting guidelines](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#porting). | Need access to a PRs labels. |
This change reduces the risk associated with a hypothetical "bad actor PR"
that tries to attack the repository or …

action: Trigger some actions on label
